apiVersion: v1
kind: Secret
metadata:
  name: iothub-grafana
  labels:
    app.kubernetes.io/name: iothub
    app.kubernetes.io/component: grafana
  namespace: monitoring
type: Opaque
data:
  admin-user: aW90LWFkbWlu
  admin-password: "cGFzc3cwcmQ="